# GET http://localhost:3003/actors

# GET http://localhost:3003/actors/Juliana

# GET http://localhost:3003/gender?gender=female

# GET http://localhost:3003/actors/gender/salary/avg?gender=female

GET http://localhost:3003/actors/004


###
DELETE http://localhost:3003/actors/006